#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  SCRIPT="$REPO_ROOT/rdg/check-sync.sh"
  PROJ="$BATS_TEST_TMPDIR/proj"
  mkdir -p "$PROJ/.ddev" "$PROJ/.platform"
  printf 'type: "php:8.3"\n' > "$PROJ/.platform.app.yaml"
  printf 'maindb:\n  type: mariadb:10.11\n' > "$PROJ/.platform/services.yaml"
}

write_generated() {
  source "$REPO_ROOT/rdg/source-hash.sh"
  local h
  h="$(rdg_source_hash "$PROJ" .platform.app.yaml .platform/services.yaml)"
  cat > "$PROJ/.ddev/config.platformsh.yaml" <<EOF
# GENERATED by 'ddev rdg-sync'. Do not edit.
# source-files: .platform.app.yaml .platform/services.yaml
# source-sha256: $h
php_version: "8.3"
EOF
}

@test "passes when the generated file matches its sources" {
  write_generated
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
}

@test "fails when a source file changed" {
  write_generated
  printf 'type: "php:8.4"\n' > "$PROJ/.platform.app.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "fails when the generated file is missing" {
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "fails when the generated file has no checksum line" {
  printf 'php_version: "8.3"\n' > "$PROJ/.ddev/config.platformsh.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
}

@test "fails when a hashed file has been deleted" {
  write_generated
  rm "$PROJ/.platform/services.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
}

@test "native mode: no app config and nothing generated, so the guard stands aside" {
  # The bug this is the fix for: on a repo that was never on Upsun the guard failed,
  # fail_on_hook_fail made that fatal, and every 'ddev start' aborted pointing at
  # 'ddev rdg-sync' -- which then died with "no .platform.app.yaml". Unstartable.
  rm -f "$PROJ/.platform.app.yaml"
  rm -rf "$PROJ/.platform"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
  # Silent: a hook that printed on every start of every native project would be
  # noise, and there is nothing for the reader to act on.
  [ -z "$output" ]
}

@test "a derived repo that lost its app config still fails, rather than going native" {
  # Why the native check tests two signals. config.platformsh.yaml existing means
  # this repo WAS derived, so a missing app config is breakage -- moved, deleted, or
  # nested deeper than derive.sh looks -- not a native project. Slipping quietly
  # into native mode here would drop the drift protection on a live Upsun project,
  # which is precisely what the guard exists to provide.
  write_generated
  rm -f "$PROJ/.platform.app.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "a source-files header with a normal multi-segment path still round-trips" {
  mkdir -p "$PROJ/web"
  printf '{}' > "$PROJ/web/package.json"
  source "$REPO_ROOT/rdg/source-hash.sh"
  local h
  h="$(rdg_source_hash "$PROJ" .platform.app.yaml .platform/services.yaml web/package.json)"
  cat > "$PROJ/.ddev/config.platformsh.yaml" <<EOF
# GENERATED by 'ddev rdg-sync'. Do not edit.
# source-files: .platform.app.yaml .platform/services.yaml web/package.json
# source-sha256: $h
php_version: "8.3"
EOF
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
}
