#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  SCRIPT="$REPO_ROOT/rdg/check-sync.sh"
  PROJ="$BATS_TEST_TMPDIR/proj"
  mkdir -p "$PROJ/.ddev" "$PROJ/.platform"
  printf 'type: "php:8.3"\n' > "$PROJ/.platform.app.yaml"
  printf 'maindb:\n  type: mariadb:10.11\n' > "$PROJ/.platform/services.yaml"
}

write_generated() {
  source "$REPO_ROOT/rdg/source-hash.sh"
  local h
  h="$(rdg_source_hash "$PROJ" .platform.app.yaml .platform/services.yaml)"
  cat > "$PROJ/.ddev/config.platformsh.yaml" <<EOF
# GENERATED by 'ddev rdg-sync'. Do not edit.
# source-files: .platform.app.yaml .platform/services.yaml
# source-sha256: $h
php_version: "8.3"
EOF
}

@test "passes when the generated file matches its sources" {
  write_generated
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
}

@test "fails when a source file changed" {
  write_generated
  printf 'type: "php:8.4"\n' > "$PROJ/.platform.app.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "fails when the generated file is missing" {
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "fails when the generated file has no checksum line" {
  printf 'php_version: "8.3"\n' > "$PROJ/.ddev/config.platformsh.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
}

@test "fails when a hashed file has been deleted" {
  write_generated
  rm "$PROJ/.platform/services.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
}

@test "native mode: no app config and nothing generated, so the guard stands aside" {
  # The bug this is the fix for: on a repo that was never on Upsun the guard failed,
  # fail_on_hook_fail made that fatal, and every 'ddev start' aborted pointing at
  # 'ddev rdg-sync' -- which then died with "no .platform.app.yaml". Unstartable.
  rm -f "$PROJ/.platform.app.yaml"
  rm -rf "$PROJ/.platform"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
  # Silent: a hook that printed on every start of every native project would be
  # noise, and there is nothing for the reader to act on.
  [ -z "$output" ]
}

@test "a derived repo that lost its app config still fails, rather than going native" {
  # Why the native check tests two signals. config.platformsh.yaml existing means
  # this repo WAS derived, so a missing app config is breakage -- moved, deleted, or
  # nested deeper than derive.sh looks -- not a native project. Slipping quietly
  # into native mode here would drop the drift protection on a live Upsun project,
  # which is precisely what the guard exists to provide.
  write_generated
  rm -f "$PROJ/.platform.app.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "a source-files header with a normal multi-segment path still round-trips" {
  mkdir -p "$PROJ/web"
  printf '{}' > "$PROJ/web/package.json"
  source "$REPO_ROOT/rdg/source-hash.sh"
  local h
  h="$(rdg_source_hash "$PROJ" .platform.app.yaml .platform/services.yaml web/package.json)"
  cat > "$PROJ/.ddev/config.platformsh.yaml" <<EOF
# GENERATED by 'ddev rdg-sync'. Do not edit.
# source-files: .platform.app.yaml .platform/services.yaml web/package.json
# source-sha256: $h
php_version: "8.3"
EOF
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
}

# --- Upsun Flex ---------------------------------------------------------------

make_flex() {
  rm -f "$PROJ/.platform.app.yaml"
  rm -rf "$PROJ/.platform"
  mkdir -p "$PROJ/.upsun"
  printf 'applications:\n  drupal:\n    type: "composable:26.05"\n' > "$PROJ/.upsun/config.yaml"
}

write_generated_flex() {
  source "$REPO_ROOT/rdg/source-hash.sh"
  local h
  h="$(rdg_source_hash "$PROJ" .upsun/config.yaml)"
  cat > "$PROJ/.ddev/config.upsun.yaml" <<EOF
# GENERATED by 'ddev rdg-sync'. Do not edit.
# source-files: .upsun/config.yaml
# source-sha256: $h
php_version: "8.4"
EOF
}

@test "flex: passes when config.upsun.yaml matches .upsun/config.yaml" {
  make_flex
  write_generated_flex
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
}

@test "flex: fails when .upsun/config.yaml changed" {
  make_flex
  write_generated_flex
  printf 'applications:\n  drupal:\n    type: "composable:25.01"\n' > "$PROJ/.upsun/config.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF 'ddev rdg-sync'
}

@test "flex: a Fixed-shaped generated file does not satisfy the guard" {
  # A repo that was Upsun Fixed and is now Flex has the old config.platformsh.yaml
  # committed. On its own it must not count as 'in sync' -- the values in it were
  # derived from files this repo no longer deploys from.
  make_flex
  printf "# GENERATED by 'ddev rdg-sync'. Do not edit.\n# source-files: .upsun/config.yaml\n# source-sha256: deadbeef\nphp_version: \"8.1\"\n" \
    > "$PROJ/.ddev/config.platformsh.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF 'config.upsun.yaml is missing'
}

@test "both generated files present: refused, naming the leftover" {
  # DDEV merges EVERY .ddev/config.*.yaml. Two of them means a stale php_version
  # and two web_extra_exposed_ports entries claiming the same container_port,
  # which DDEV rejects at parse time -- so every later ddev command fails too,
  # including the 'ddev rdg-sync' that would fix it. Refuse here, where the
  # message can still be read.
  make_flex
  write_generated_flex
  printf "# GENERATED by 'ddev rdg-sync'. Do not edit.\nphp_version: \"8.1\"\n" \
    > "$PROJ/.ddev/config.platformsh.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF 'both .ddev/config.platformsh.yaml and .ddev/config.upsun.yaml'
  printf '%s' "$output" | grep -qF 'config.platformsh.yaml is a leftover'
}

@test "both generated files present on a Fixed repo: the Flex one is the leftover" {
  write_generated
  printf "# GENERATED by 'ddev rdg-sync'. Do not edit.\nphp_version: \"8.4\"\n" \
    > "$PROJ/.ddev/config.upsun.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF 'config.upsun.yaml is a leftover'
}

@test "flex: leftover Fixed config on disk does not make the guard look at it" {
  # The real converted-repo shape: .upsun/config.yaml is live, and an untracked
  # .platform/ plus a .platform.app.yaml that came back with a branch checkout are
  # sitting beside it. Editing either must not be reported as drift, because
  # neither is in the source-files header.
  make_flex
  write_generated_flex
  mkdir -p "$PROJ/.platform"
  printf 'type: "php:8.1"\n' > "$PROJ/.platform.app.yaml"
  printf 'olddb:\n  type: mariadb:10.6\n' > "$PROJ/.platform/services.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
}

@test "a native repo holding a generated Flex config still fails, not goes quiet" {
  # Same reasoning as the Fixed case above: a generated file means this repo WAS
  # derived, so losing the hosting config is breakage, not a move to native mode.
  make_flex
  write_generated_flex
  rm "$PROJ/.upsun/config.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
}
