#!/usr/bin/env bats

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  SCRIPT="$REPO_ROOT/rdg/check-sync.sh"
  PROJ="$BATS_TEST_TMPDIR/proj"
  mkdir -p "$PROJ/.ddev" "$PROJ/.platform"
  printf 'type: "php:8.3"\n' > "$PROJ/.platform.app.yaml"
  printf 'maindb:\n  type: mariadb:10.11\n' > "$PROJ/.platform/services.yaml"
}

write_generated() {
  source "$REPO_ROOT/rdg/source-hash.sh"
  local h
  h="$(rdg_source_hash "$PROJ" .platform.app.yaml .platform/services.yaml)"
  cat > "$PROJ/.ddev/config.platformsh.yaml" <<EOF
# GENERATED by 'ddev rdg-sync'. Do not edit.
# source-files: .platform.app.yaml .platform/services.yaml
# source-sha256: $h
php_version: "8.3"
EOF
}

@test "passes when the generated file matches its sources" {
  write_generated
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -eq 0 ]
}

@test "fails when a source file changed" {
  write_generated
  printf 'type: "php:8.4"\n' > "$PROJ/.platform.app.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "fails when the generated file is missing" {
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
  printf '%s' "$output" | grep -qF "ddev rdg-sync"
}

@test "fails when the generated file has no checksum line" {
  printf 'php_version: "8.3"\n' > "$PROJ/.ddev/config.platformsh.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
}

@test "fails when a hashed file has been deleted" {
  write_generated
  rm "$PROJ/.platform/services.yaml"
  run bash "$SCRIPT" "$PROJ"
  [ "$status" -ne 0 ]
}
