#!/usr/bin/env bash
#ddev-generated
# Writes the two files that put Mailpit's UI on a hostname instead of a port.
#
# Called from install.yaml's post_install_actions (so every repo gets it, in both
# modes, without anyone remembering) and again from 'ddev rdg-sync' (so a project
# rename self-heals on the next sync rather than silently handing the Mailpit
# hostname to the app).
#
# Runs on the HOST, with .ddev as the working directory. No yq: the project name
# comes from a one-line sed over .ddev/config.yaml, which is the same file DDEV
# reads it from.
#
# Why this is worth automating rather than documenting: DDEV serves Mailpit on
# mailpit_http_port / mailpit_https_port against the BARE project hostname, and
# those ports are global -- one ddev-router serves every project, so two projects
# on the default 8025/8026 means "whoever started first wins" and you silently read
# the wrong project's mail. A hostname is per-project by construction, so the
# collision cannot happen and nobody has to hand out port numbers.
set -euo pipefail

ddev_dir="${1:-$PWD}"
ddev_dir="${ddev_dir%/}"

router="$ddev_dir/traefik/config/mailpit.yaml"
hostname_config="$ddev_dir/config.mailpit.yaml"

project="$(sed -n 's/^name:[[:space:]]*//p' "$ddev_dir/config.yaml" 2>/dev/null | head -1)"
project="${project%\"}"; project="${project#\"}"
project="${project%\'}"; project="${project#\'}"

if [ -z "$project" ]; then
  # Not fatal. A project with no explicit name takes the enclosing directory's
  # name, which this cannot see reliably, and a wrong guess would route the
  # Mailpit hostname at the app. Saying nothing happened is the honest outcome.
  printf 'rdg: no "name:" in .ddev/config.yaml, so Mailpit keeps its port-based URL.\n' >&2
  exit 0
fi

# A name that is not a DNS label would produce a hostname nothing can reach and a
# Traefik rule that does not compile. Refusing beats emitting a broken router.
case "$project" in
  ''|*[!a-zA-Z0-9-]*)
    printf 'rdg: project name "%s" is not a DNS label, so Mailpit keeps its port-based URL.\n' "$project" >&2
    exit 0
    ;;
esac

mkdir -p "$(dirname "$router")"

# Deliberately NO '#ddev-generated' marker on either file. DDEV regenerates
# traefik/config/ and rewrites config.*.yaml it owns, and it decides what it owns
# by that marker -- so carrying it would mean the router disappears on the next
# restart. install.yaml's removal_actions delete both by name instead.
cat > "$router" <<EOF
# GENERATED by the ddev-rdg add-on. Do not edit.
# Regenerated by 'ddev rdg-sync'; re-run 'ddev add-on get' after a project rename
# on a repo that is not on Upsun.
#
# Mailpit's UI on a hostname instead of a port. DDEV has no setting for this: it
# serves the UI on mailpit_http_port / mailpit_https_port against the bare project
# hostname. Those ports are global -- one ddev-router serves every project -- so
# two projects on the default 8025/8026 means whoever started first wins, and you
# read the wrong project's mail without being told. A hostname cannot collide.
#
# SMTP is untouched: the app still sends to localhost:1025 inside the web
# container, and the port-based URL keeps working too.
#
# 'priority' matters. config.mailpit.yaml registers this hostname, and DDEV
# generates its own router for it pointing at the web container's port 80 -- i.e.
# at the application. Both match the same Host rule, so this one has to outrank it.
http:
  routers:
    $project-mailpit-ui:
      entrypoints:
        - http-443
      rule: HostRegexp(\`^mailpit\\.$project\\.ddev\\.site\$\`)
      service: $project-mailpit-ui
      priority: 100
      tls: true

  services:
    $project-mailpit-ui:
      loadbalancer:
        servers:
          - url: http://ddev-$project-web:8025
EOF

# Its own config file rather than an edit to config.yaml: that one belongs to the
# repo. additional_hostnames is a list key, and DDEV APPENDS list keys when it
# merges config.*.yaml, so this adds to whatever the project already declares
# instead of replacing it.
cat > "$hostname_config" <<EOF
# GENERATED by the ddev-rdg add-on. Do not edit.
#
# Registers mailpit.$project.ddev.site for DNS and, more importantly, for the
# mkcert certificate: the cert's '*.ddev.site' wildcard matches a SINGLE label, so
# it does not cover a subdomain of the project host. Without this the hostname
# resolves and then fails TLS, which presents as a certificate error rather than
# as a missing route.
#
# The route itself is traefik/config/mailpit.yaml.
additional_hostnames:
    - mailpit.$project
EOF

printf 'Mailpit UI: https://mailpit.%s.ddev.site\n' "$project"
