#!/usr/bin/env bash
#ddev-generated
# Generates nginx location blocks for web.locations that live outside the
# docroot. Prints nothing when there are none.
#
# Third argument: the application name, on Upsun Flex only. Flex holds the app's
# keys under .applications.<name> in .upsun/config.yaml, where Fixed has them at
# the root of .platform.app.yaml; passing the name rather than a yq expression
# keeps the caller (a host script, shelling in through 'ddev exec') from having
# to quote one across the container boundary.
set -euo pipefail

usage='usage: nginx-locations.sh <app-config-path> <docroot> <app-root> [app-name]'
app_config="${1:?$usage}"
docroot="${2:?$usage}"
docroot="${docroot%/}"
# Required, and the empty string is a legitimate value meaning "the app is at the
# repo root" -- hence ${3?} (set-or-fail) rather than ${3:?} (non-empty-or-fail).
# Required rather than inferred, because it used to be inferred and the inference
# was wrong: see the comment above container_app_root.
app_root="${3?$usage}"
app_root="${app_root%/}"
app_name="${4:-}"

if [ -n "$app_name" ]; then
  export app_name
  app_expr='.applications[strenv(app_name)]'
else
  app_expr='.'
fi

note() { printf 'rdg-sync: %s\n' "$*" >&2; }

# Both of these used to be derived from the docroot alone -- app root as
# dirname($docroot), app-relative web root as basename($docroot) -- which silently
# assumes the docroot is exactly ONE segment below the app root. It usually is
# ('drupal' + 'web'), and it is not always: an app at the repo root declaring
# `root: 'drupal/web'` breaks both halves at once.
#
#   container_app_root  became /var/www/html/drupal, so every emitted path gained a
#                       duplicate segment: /var/www/html/drupal/drupal/web/...
#   web_root_name       became 'web', so the "already inside the docroot" test below
#                       stopped matching roots like 'drupal/web/sites/default/files'
#                       and emitted blocks nginx already serves.
#
# The caller knows both values exactly, so it passes the app root and this derives
# the web root by subtraction. No depth assumption survives.
container_app_root="/var/www/html"
[ -n "$app_root" ] && container_app_root="/var/www/html/$app_root"

# The docroot relative to the app root: 'web', or 'drupal/web', or whatever depth
# the app actually declares. Stripping the prefix rather than taking a basename is
# what keeps a multi-segment web root intact.
web_root_rel="$docroot"
if [ -n "$app_root" ]; then
  case "$docroot" in
    "$app_root"/*) web_root_rel="${docroot#"$app_root"/}" ;;
    "$app_root")   web_root_rel="" ;;
    *)
      printf 'rdg-sync: warning: docroot %s is not under app root %s; skipping the nginx snippet\n' \
        "$docroot" "$app_root" >&2
      exit 0
      ;;
  esac
fi

blocks=""
while IFS=$'\t' read -r location location_root location_scripts; do
  [ -n "$location" ] || continue
  [ "$location" = "/" ] && continue
  # nginx already serves anything under the docroot. Compared against the
  # APP-RELATIVE docroot, because web.locations roots are app-relative too.
  case "$location_root" in
    "$web_root_rel"|"$web_root_rel"/*) continue ;;
  esac

  # A location with 'scripts: true' is a PHP entry point, not a static tree --
  # it needs fastcgi_pass and a SCRIPT_FILENAME, which is a different block
  # shape and depends on the socket path of whatever webserver_type the project
  # runs. Emitting the static block below for it would answer every request with
  # a confident 404, which is worse than emitting nothing and saying so.
  if [ "$location_scripts" = "true" ]; then
    note "web.locations '$location' runs scripts, so it needs a FastCGI block rather than a static one; write it by hand in .ddev/nginx/*.conf"
    continue
  fi

  target="$container_app_root/${location_root#/}"
  location_name="${location#/}"

  # 'root' rewrites <location> onto the end of the path, so it only works when
  # the last path segment equals the location name. Otherwise use 'alias'.
  if [ "$(basename "$location_root")" = "$location_name" ]; then
    directive="root $(dirname "$target");"
  else
    directive="alias $target;"
  fi

  blocks+="
location ^~ $location {
    $directive
    try_files \$uri \$uri/index.html =404;
}
"
done < <(yq -r "$app_expr | .web.locations // {} | to_entries | .[]
                | select(.value.root != null)
                | .key + \"\t\" + .value.root + \"\t\" + ((.value.scripts // false) | tostring)" "$app_config")

[ -n "$blocks" ] || exit 0

cat <<'EOF'
# GENERATED by 'ddev rdg-sync'. Do not edit.
# Mirrors the web.locations in the Upsun app config that live outside the docroot.
#
# '^~' prefix matching is deliberate. DDEV's nginx-site.conf declares regex
# locations for .js/.css and for images BEFORE its include of
# /mnt/ddev_config/nginx/*.conf, so a regex location here would lose every
# asset request under these paths to the Drupal docroot.
EOF
printf '%s' "$blocks"
