#!/usr/bin/env bash
#ddev-generated
# Generates nginx location blocks for web.locations that live outside the
# docroot. Prints nothing when there are none.
#
# Third argument: the application name, on Upsun Flex only. Flex holds the app's
# keys under .applications.<name> in .upsun/config.yaml, where Fixed has them at
# the root of .platform.app.yaml; passing the name rather than a yq expression
# keeps the caller (a host script, shelling in through 'ddev exec') from having
# to quote one across the container boundary.
set -euo pipefail

app_config="${1:?usage: nginx-locations.sh <app-config-path> <docroot> [app-name]}"
docroot="${2:?usage: nginx-locations.sh <app-config-path> <docroot> [app-name]}"
docroot="${docroot%/}"
app_name="${3:-}"

if [ -n "$app_name" ]; then
  export app_name
  app_expr='.applications[strenv(app_name)]'
else
  app_expr='.'
fi

note() { printf 'rdg-sync: %s\n' "$*" >&2; }

app_dir_rel="$(dirname "$docroot")"     # repo-relative app root, or '.' at root
web_root_name="$(basename "$docroot")"  # the app-relative docroot, e.g. 'web'

container_app_root="/var/www/html"
[ "$app_dir_rel" != "." ] && container_app_root="/var/www/html/$app_dir_rel"

blocks=""
while IFS=$'\t' read -r location location_root location_scripts; do
  [ -n "$location" ] || continue
  [ "$location" = "/" ] && continue
  # nginx already serves anything under the docroot.
  case "$location_root" in
    "$web_root_name"|"$web_root_name"/*) continue ;;
  esac

  # A location with 'scripts: true' is a PHP entry point, not a static tree --
  # it needs fastcgi_pass and a SCRIPT_FILENAME, which is a different block
  # shape and depends on the socket path of whatever webserver_type the project
  # runs. Emitting the static block below for it would answer every request with
  # a confident 404, which is worse than emitting nothing and saying so.
  if [ "$location_scripts" = "true" ]; then
    note "web.locations '$location' runs scripts, so it needs a FastCGI block rather than a static one; write it by hand in .ddev/nginx/*.conf"
    continue
  fi

  target="$container_app_root/${location_root#/}"
  location_name="${location#/}"

  # 'root' rewrites <location> onto the end of the path, so it only works when
  # the last path segment equals the location name. Otherwise use 'alias'.
  if [ "$(basename "$location_root")" = "$location_name" ]; then
    directive="root $(dirname "$target");"
  else
    directive="alias $target;"
  fi

  blocks+="
location ^~ $location {
    $directive
    try_files \$uri \$uri/index.html =404;
}
"
done < <(yq -r "$app_expr | .web.locations // {} | to_entries | .[]
                | select(.value.root != null)
                | .key + \"\t\" + .value.root + \"\t\" + ((.value.scripts // false) | tostring)" "$app_config")

[ -n "$blocks" ] || exit 0

cat <<'EOF'
# GENERATED by 'ddev rdg-sync'. Do not edit.
# Mirrors the web.locations in the Upsun app config that live outside the docroot.
#
# '^~' prefix matching is deliberate. DDEV's nginx-site.conf declares regex
# locations for .js/.css and for images BEFORE its include of
# /mnt/ddev_config/nginx/*.conf, so a regex location here would lose every
# asset request under these paths to the Drupal docroot.
EOF
printf '%s' "$blocks"
