#!/usr/bin/env bash
# Generates nginx location blocks for web.locations that live outside the
# docroot. Prints nothing when there are none.
set -euo pipefail

app_config="${1:?usage: nginx-locations.sh <app-config-path> <docroot>}"
docroot="${2:?usage: nginx-locations.sh <app-config-path> <docroot>}"
docroot="${docroot%/}"

app_dir_rel="$(dirname "$docroot")"     # repo-relative app root, or '.' at root
web_root_name="$(basename "$docroot")"  # the app-relative docroot, e.g. 'web'

container_app_root="/var/www/html"
[ "$app_dir_rel" != "." ] && container_app_root="/var/www/html/$app_dir_rel"

blocks=""
while IFS=$'\t' read -r location location_root; do
  [ -n "$location" ] || continue
  [ "$location" = "/" ] && continue
  # nginx already serves anything under the docroot.
  case "$location_root" in
    "$web_root_name"|"$web_root_name"/*) continue ;;
  esac

  target="$container_app_root/${location_root#/}"
  location_name="${location#/}"

  # 'root' rewrites <location> onto the end of the path, so it only works when
  # the last path segment equals the location name. Otherwise use 'alias'.
  if [ "$(basename "$location_root")" = "$location_name" ]; then
    directive="root $(dirname "$target");"
  else
    directive="alias $target;"
  fi

  blocks+="
location ^~ $location {
    $directive
    try_files \$uri \$uri/index.html =404;
}
"
done < <(yq -r '.web.locations // {} | to_entries | .[]
                | select(.value.root != null)
                | .key + "\t" + .value.root' "$app_config")

[ -n "$blocks" ] || exit 0

cat <<'EOF'
# GENERATED by 'ddev rdg-sync'. Do not edit.
# Mirrors the web.locations in .platform.app.yaml that live outside the docroot.
#
# '^~' prefix matching is deliberate. DDEV's nginx-site.conf declares regex
# locations for .js/.css and for images BEFORE its include of
# /mnt/ddev_config/nginx/*.conf, so a regex location here would lose every
# asset request under these paths to the Drupal docroot.
EOF
printf '%s' "$blocks"
